version: "3"

services:
    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginx
        restart: always
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    express:
        build:
            context: .
            dockerfile: ./docker/express/Dockerfile
        container_name: express
        restart: always
        env_file:
            - .env
